/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#ifndef PLUGINPROCESSOR_H_INCLUDED
#define PLUGINPROCESSOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "Vibrato.h"

//==============================================================================
/**
*/
class VibratoPluginAudioProcessor  : public AudioProcessor
{
public:
    //==============================================================================
    VibratoPluginAudioProcessor();
    ~VibratoPluginAudioProcessor();
    
    //==============================================================================
    void prepareToPlay (double sampleRate, int samplesPerBlock) override;
    void releaseResources() override;

    void processBlock (AudioSampleBuffer& buffer) override;
    void processBlockBypassed (AudioBuffer<float>& buffer) override;

    //==============================================================================
    AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override;
    double getTailLengthSeconds() const override;
    
    //==============================================================================
    const String getName() const override;

    //==============================================================================
    int getNumPrograms() override;
    int getCurrentProgram() override;
    const String getProgramName (int index) override;

    //==============================================================================
    void getStateInformation (MemoryBlock& destData) override;
    void setStateInformation (const void* data, int sizeInBytes) override;
    
    //==============================================================================
    void setParameter (int parameterIndex, float newValue) override;
    float getParameter (int parameterIndex) override;
    
    //======= variable
    float fModFreqInHz=0.F;
    float fModWidthInSec = 0.F;

private:
    //==============================================================================
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (VibratoPluginAudioProcessor)
    CVibrato *m_pCVib;
};


#endif  // PLUGINPROCESSOR_H_INCLUDED
